// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WwEDvmNLbp_3lbS6krBvAQ4bmHATsG8',
    appId: '1:702871066802:web:e113ca55dc6170d5bbd1ab',
    messagingSenderId: '702871066802',
    projectId: 'nwader-697f7',
    authDomain: 'nwader-697f7.firebaseapp.com',
    storageBucket: 'nwader-697f7.appspot.com',
    measurementId: 'G-S7KHXPM9KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qebhyMJ_pUvwa6Un6pwm31QbYF7Q9qA',
    appId: '1:702871066802:android:7afbfa6aaa50de53bbd1ab',
    messagingSenderId: '702871066802',
    projectId: 'nwader-697f7',
    storageBucket: 'nwader-697f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-uy639R8O9gDSjH9NbiyxN-6MSsu-l44',
    appId: '1:702871066802:ios:7d625859816c450fbbd1ab',
    messagingSenderId: '702871066802',
    projectId: 'nwader-697f7',
    storageBucket: 'nwader-697f7.appspot.com',
    iosClientId: '702871066802-aos8e4r72i7sp2btha58docstsjeqgnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );
}
